// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAamSEf36YuhAwQO-L9XAnL_MNdyVBMKdg',
    appId: '1:87639162167:web:a004ad5f2d16bbdd846eb2',
    messagingSenderId: '87639162167',
    projectId: 'plango-4e23f',
    authDomain: 'plango-4e23f.firebaseapp.com',
    storageBucket: 'plango-4e23f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnoLE7gwxMDN3gQkgylGkg7UHTeLCiyyc',
    appId: '1:87639162167:android:46c737d38c4082f2846eb2',
    messagingSenderId: '87639162167',
    projectId: 'plango-4e23f',
    storageBucket: 'plango-4e23f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnQxykeOC0v__ihwA0KAA37u6Ytg4hUnk',
    appId: '1:87639162167:ios:96ead5c47328a3c7846eb2',
    messagingSenderId: '87639162167',
    projectId: 'plango-4e23f',
    storageBucket: 'plango-4e23f.firebasestorage.app',
    iosBundleId: 'com.example.plango',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYXBJoPKr8zwp9CAxOwVcl0r9YpJRCWVI',
    appId: '1:759037506750:ios:6abd4c7d1a9e41f1abdaef',
    messagingSenderId: '759037506750',
    projectId: 'plango-3f14a',
    storageBucket: 'plango-3f14a.firebasestorage.app',
    iosBundleId: 'com.example.plango',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4VUgp6cJlHNxSRlvWDzO7U4ePpPGBelE',
    appId: '1:759037506750:web:3f3122cccb763f53abdaef',
    messagingSenderId: '759037506750',
    projectId: 'plango-3f14a',
    authDomain: 'plango-3f14a.firebaseapp.com',
    storageBucket: 'plango-3f14a.firebasestorage.app',
  );
}
